import { useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, BadgePlus, CalendarDays, Check, ChevronDown, CircleHelp, Coffee, CreditCard, Ellipsis, House, LayoutDashboard, MessageSquareText, PieChart, Plus, Search, ShoppingBasket, Sparkles, Trash2, TrendingUp, Wallet, X } from 'lucide-react';

const categories = [
 {name:'Supermercado',color:'#39745b',icon:ShoppingBasket,keys:['supermercado','super','almacen','almacén','verduleria','verdulería']},
 {name:'Comida fuera',color:'#e2a95b',icon:Coffee,keys:['comida','restaurante','cafe','café','bar','delivery']},
 {name:'Hogar y servicios',color:'#6c8ba8',icon:House,keys:['servicios','hogar','alquiler','expensas','luz','gas','agua','internet']},
 {name:'Transporte',color:'#8974b2',icon:ArrowUpRight,keys:['transporte','sube','nafta','taxi','uber','colectivo']},
 {name:'Salud',color:'#d87970',icon:Plus,keys:['salud','farmacia','medico','médico','dentista']},
 {name:'Suscripciones',color:'#539c8c',icon:CreditCard,keys:['suscripciones','spotify','netflix']},
 {name:'Ropa',color:'#d47e9a',icon:BadgePlus,keys:['ropa','vestimenta','zapatillas']},
 {name:'Ocio',color:'#c8874e',icon:Sparkles,keys:['ocio','gustos','entretenimiento','cine','salida']},
 {name:'Educación',color:'#87945a',icon:CircleHelp,keys:['educacion','educación','curso','libro']},
 {name:'Otros',color:'#999e98',icon:Ellipsis,keys:['otros','otro']}
];
const storageKey='control-gastos-v2', financeKey='control-gastos-financial-v1', closingKey='control-gastos-closing-v1';
const cardOptions=['Efectivo','Débito','YOY','Visa Galicia','Mastercard Galicia','Galicia Mas','Otra tarjeta'];
const creditCards=['YOY','Visa Galicia','Mastercard Galicia','Galicia Mas','Otra tarjeta'];
const closingDays={YOY:23,'Visa Galicia':30,'Mastercard Galicia':30,'Galicia Mas':30,'Otra tarjeta':30};
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(n||0);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const norm=s=>s.toLocaleLowerCase('es-AR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const isCredit=payment=>creditCards.includes(payment)||/tarjeta|yoy|visa|mastercard|galicia/i.test(payment||'');
function monthAfter(value,count=1){const[y,m]=value.split('-').map(Number),d=new Date(y,m-1+count,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function defaultClose(card,month){const[y,m]=month.split('-').map(Number),day=Math.min(closingDays[card]||30,new Date(y,m,0).getDate());return `${month}-${String(day).padStart(2,'0')}`}
function closeDate(card,month,closings){return closings[month]?.[card]||defaultClose(card,month)}
function firstChargeMonth(date,payment,closings){const purchaseMonth=date.slice(0,7);if(!isCredit(payment))return purchaseMonth;const close=closeDate(payment,purchaseMonth,closings);return date>=close?monthAfter(purchaseMonth):purchaseMonth}
function dueForMonth(expense,month){if(isCredit(expense.payment)){const start=expense.firstMonth||expense.date.slice(0,7);const index=(Number(month.slice(0,4))-Number(start.slice(0,4)))*12+Number(month.slice(5,7))-Number(start.slice(5,7));const count=Math.max(1,Number(expense.installments)||1);if(index<0||index>=count)return null;const totalCents=Math.round(Number(expense.amount)*100),base=Math.floor(totalCents/count),cents=index===count-1?totalCents-base*(count-1):base;return {amount:cents/100,index:index+1,count}}
 return expense.date.slice(0,7)===month?{amount:Number(expense.amount),index:1,count:1}:null}
function monthTotal(expenses,month){return expenses.reduce((sum,expense)=>sum+(dueForMonth(expense,month)?.amount||0),0)}
function load(){try{return JSON.parse(localStorage.getItem(storageKey)||'[]').map(x=>{let payment=x.payment||'';if(/efectivo/i.test(payment))payment='Efectivo';else if(/d[eé]bito|d[eé]bit/i.test(payment))payment='Débito';else if(/master/i.test(payment))payment='Mastercard Galicia';else if(/visa/i.test(payment))payment='Visa Galicia';else if(/yoy/i.test(payment))payment='YOY';else if(/galicia/i.test(payment))payment='Galicia Mas';else if(/tarjeta|cr[eé]dito/i.test(payment))payment='Otra tarjeta';return {...x,payment,installments:Math.max(1,Number(x.installments)||1),firstMonth:x.firstMonth||x.date?.slice(0,7)}})}catch{return []}}
function loadObject(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}
function balanceThrough(expenses,finance,month){const[targetYear,targetMonth]=month.split('-').map(Number),years=[targetYear,...Object.keys(finance).map(m=>Number(m.slice(0,4))),...expenses.flatMap(x=>[Number(x.date.slice(0,4)),Number((x.firstMonth||x.date.slice(0,7)).slice(0,4))])],firstYear=Math.min(...years);let balance=Number(finance[`${firstYear}-01`]?.openingBalance)||0;for(let y=firstYear;y<=targetYear;y++){const last=y===targetYear?targetMonth:12;for(let n=1;n<=last;n++){const m=`${y}-${String(n).padStart(2,'0')}`,values=finance[m]||{};balance+=Number(values.salary||0)+Number(values.internet||0)-monthTotal(expenses,m)-Number(values.investments||0)}}return balance}
function parseExpense(text,closings){
 const match=text.match(/(?:\$\s*)?(\d[\d.,]*)\s*(?:pesos?|ars)?/i);if(!match)return null;let amount=match[1];
 if(amount.includes('.')&&amount.includes(','))amount=amount.replace(/\./g,'').replace(',','.');else if(amount.includes(','))amount=amount.replace(',','.');else if(/^\d{1,3}(?:\.\d{3})+$/.test(amount))amount=amount.replace(/\./g,'');
 amount=Number(amount);if(!Number.isFinite(amount)||amount<=0)return null;const clean=norm(text);
 const categoryText=text.match(/categor[ií]a\s+(.+?)(?:\s+(?:con|usando|en)\b|$)/i)?.[1]?.trim();
 const category=(categoryText&&categories.find(c=>norm(c.name)===norm(categoryText)))||categories.find(c=>c.keys.some(k=>clean.includes(norm(k))))||categories.at(-1);
 const found=creditCards.find(card=>clean.includes(norm(card)))||(/\byoy\b/i.test(clean)?'YOY':/visa/i.test(clean)?'Visa Galicia':/master\s?card/i.test(clean)?'Mastercard Galicia':/galicia\s?mas/i.test(clean)?'Galicia Mas':'');const raw=text.match(/(?:con|usando)\s+(?:la\s+)?(tarjeta(?:\s+(?:de\s+)?[\p{L}\d-]+)?|efectivo|d[eé]bito|cr[eé]dito)/iu)?.[1]||'';const payment=found||(/efectivo/i.test(raw)?'Efectivo':/d[eé]bito/i.test(raw)?'Débito':/tarjeta|cr[eé]dito/i.test(raw)?'Otra tarjeta':'');
 let description=text.match(/\ben\s+(?:un\s+|una\s+|el\s+|la\s+)?(.+?)(?:\s+categor[ií]a\b|$)/i)?.[1]?.trim()||'';
 description=description.replace(/\s+(?:con|usando)\s+(?:la\s+)?tarjeta\b.*$/i,'').replace(/^(?:un|una|el|la)\s+/i,'').trim();
 const date=today(),method=payment||'Efectivo';return {amount,date,category:category.name,payment:method,description,installments:1,firstMonth:firstChargeMonth(date,method,closings)};
}
function Donut({items,total}){let offset=0;const circumference=2*Math.PI*74;return <div className="donut-wrap"><svg viewBox="0 0 180 180" className="donut"><circle cx="90" cy="90" r="74" fill="none" stroke="#eef0ec" strokeWidth="20"/>{items.map(item=>{const length=total?item.amount/total*circumference:0;const node=<circle key={item.name} cx="90" cy="90" r="74" fill="none" stroke={item.color} strokeWidth="20" strokeDasharray={`${length} ${circumference-length}`} strokeDashoffset={-offset} strokeLinecap="round"/>;offset+=length+3;return node})}</svg><div className="donut-center"><span>Gasto total</span><strong>{money(total)}</strong><small>este mes</small></div></div>}
function previousMonth(value){const[y,m]=value.split('-').map(Number);const d=new Date(y,m-2,15);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}

export default function App(){
 const[expenses,setExpenses]=useState(load),[month,setMonth]=useState(today().slice(0,7)),[phrase,setPhrase]=useState(''),[draft,setDraft]=useState(null),[filter,setFilter]=useState('Todos'),[finance,setFinance]=useState(()=>loadObject(financeKey)),[closings,setClosings]=useState(()=>loadObject(closingKey));
 const visible=useMemo(()=>expenses.map(x=>({...x,due:dueForMonth(x,month)})).filter(x=>x.due),[expenses,month]);
 const total=visible.reduce((s,x)=>s+x.due.amount,0);
 const grouped=categories.map(c=>({...c,amount:visible.filter(x=>x.category===c.name).reduce((s,x)=>s+x.due.amount,0)})).filter(x=>x.amount>0).sort((a,b)=>b.amount-a.amount);
 const previous=monthTotal(expenses,previousMonth(month));
 const difference=previous?Math.round((total-previous)/previous*100):null;
 let recent=[...visible].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt);
 if(filter.startsWith('search:'))recent=recent.filter(x=>`${x.description} ${x.category} ${x.payment}`.toLowerCase().includes(filter.slice(7)));else if(filter!=='Todos')recent=recent.filter(x=>x.payment===filter);
 const monthlyFinance=finance[month]||{};
 const yearMonths=[...Object.keys(finance),...expenses.map(x=>x.date.slice(0,7)),...expenses.map(x=>x.firstMonth||x.date.slice(0,7))];const firstYear=yearMonths.length?Math.min(...yearMonths.map(m=>Number(m.slice(0,4)))):Number(month.slice(0,4));const carried=month.endsWith('-01')?(Number(month.slice(0,4))>firstYear?balanceThrough(expenses,finance,previousMonth(month)):Number(finance[month]?.openingBalance||0)):balanceThrough(expenses,finance,previousMonth(month));
 const available=balanceThrough(expenses,finance,month);
 const cardTotals=creditCards.map(card=>({card,amount:visible.filter(x=>x.payment===card).reduce((s,x)=>s+x.due.amount,0)}));
 function persist(next){setExpenses(next);localStorage.setItem(storageKey,JSON.stringify(next))}
 function setMonthly(field,value){const next={...finance,[month]:{...monthlyFinance,[field]:value}};setFinance(next);localStorage.setItem(financeKey,JSON.stringify(next))}
 function setClosing(card,value){const next={...closings,[month]:{...(closings[month]||{}),[card]:value}};setClosings(next);localStorage.setItem(closingKey,JSON.stringify(next));if(draft?.payment===card)setDraft({...draft,firstMonth:firstChargeMonth(draft.date,card,next)})}
 function changeDraft(field,value){const next={...draft,[field]:value};if(field==='date'||field==='payment')next.firstMonth=firstChargeMonth(next.date,next.payment,closings);if(field==='payment'&&!isCredit(value))next.installments=1;setDraft(next)}
 function interpret(e){e.preventDefault();const value=parseExpense(phrase,closings);if(!value){window.alert('No encontré el importe. Probá: “Gasté 100 pesos en un yogurt”.');return}setDraft(value)}
 function saveExpense(e){e.preventDefault();persist([...expenses,{...draft,amount:Number(draft.amount),installments:Math.max(1,Number(draft.installments)||1),id:crypto.randomUUID(),createdAt:Date.now()}]);setDraft(null);setPhrase('')}
 const biggest=grouped[0];
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="#inicio"><span className="brand-mark"><Wallet size={19}/></span><span>control<span className="brand-dot">.</span><small>FINANZAS PERSONALES</small></span></a><div className="side-label">MENÚ PRINCIPAL</div><nav className="main-nav"><a className="nav-item active" href="#inicio"><LayoutDashboard/>Resumen</a><a className="nav-item" href="#movimientos"><ArrowDownLeft/>Movimientos</a><a className="nav-item" href="#categorias"><PieChart/>Categorías</a><a className="nav-item" href="#finanzas"><Wallet/>Finanzas</a><a className="nav-item" href="#tarjetas"><CreditCard/>Tarjetas</a></nav><div className="side-label accounts-label">TUS CUENTAS</div><div className="account-item"><i className="account-dot cash"/><span>Efectivo</span><span className="account-type">ARS</span></div><div className="account-item"><i className="account-dot card"/><span>Tarjetas</span><span className="account-type">4</span></div><div className="sidebar-spacer"/><div className="sidebar-tip"><span className="tip-icon"><Sparkles size={15}/></span><strong>Un hábito a la vez</strong><p>Un registro rápido hoy te da más claridad mañana.</p></div><div className="profile"><div className="avatar">M</div><div><strong>Mis finanzas</strong><small>Cuenta personal</small></div><Ellipsis className="profile-more"/></div></aside>
  <main className="main-content" id="inicio">
   <header className="page-header"><div><div className="breadcrumb">Inicio <span>/</span> Resumen</div><h1>Buen día <span className="wave">✳</span></h1><p>Así se están moviendo tus gastos.</p></div><div className="header-actions"><button className="icon-button" aria-label="Buscar"><Search/></button><button className="help-button"><CircleHelp/> Ayuda</button><div className="avatar header-avatar">M</div></div></header>
   <section className="quick-card"><div className="quick-orb orb-one"/><div className="quick-orb orb-two"/><div className="quick-content"><span className="quick-kicker"><Sparkles/> REGISTRO INTELIGENTE</span><h2>¿Qué gastaste hoy?</h2><p>Escribilo como te salga. Nosotros ordenamos los detalles.</p><form onSubmit={interpret} className="quick-form"><MessageSquareText className="input-icon"/><input value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder="Ej: Gasté $8.500 en el súper con Visa" aria-label="Describí el gasto"/><button>Registrar <ArrowRight/></button></form><div className="quick-examples"><span>Probá:</span><button type="button" onClick={()=>setPhrase('Gasté 3.500 pesos en un café categoría Comida fuera')}>☕ Café</button><button type="button" onClick={()=>setPhrase('Gasté 12.000 pesos con la tarjeta Visa en un supermercado categoría Supermercado')}>🛒 Supermercado</button></div>
   {draft&&<div className="draft-panel"><div className="draft-title"><span><Check/> Entendimos tu gasto</span><button type="button" className="close-draft" onClick={()=>setDraft(null)}><X/></button></div><form onSubmit={saveExpense} className="draft-fields"><label>Fecha de compra<input type="date" value={draft.date} onChange={e=>changeDraft('date',e.target.value)} required/></label><label>Importe total<div className="currency-field"><span>$</span><input type="number" min="0.01" step="0.01" value={draft.amount} onChange={e=>changeDraft('amount',e.target.value)} required/></div></label><label>Descripción<input value={draft.description} onChange={e=>changeDraft('description',e.target.value)} placeholder="Descripción" required/></label><label>Categoría<select value={draft.category} onChange={e=>changeDraft('category',e.target.value)}>{categories.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>Tarjeta o medio<select value={draft.payment} onChange={e=>changeDraft('payment',e.target.value)}>{cardOptions.map(c=><option key={c}>{c}</option>)}</select></label><label>Cuotas<select value={draft.installments} disabled={!isCredit(draft.payment)} onChange={e=>changeDraft('installments',Number(e.target.value))}>{Array.from({length:24},(_,i)=><option key={i+1} value={i+1}>{i+1} {i?'cuotas':'cuota'}</option>)}</select></label><label>Primera cuota entra en<input type="month" value={draft.firstMonth} onChange={e=>changeDraft('firstMonth',e.target.value)} required/></label><p className="closing-note">{isCredit(draft.payment)?`Cierre ${new Date(`${closeDate(draft.payment,draft.date.slice(0,7),closings)}T12:00:00`).toLocaleDateString('es-AR')} · Cuota mensual aproximada ${money(Number(draft.amount)/Math.max(1,Number(draft.installments)))}`:'El gasto se asigna al mes de compra.'}</p><button className="confirm-button">Guardar gasto <Check/></button></form></div>}</div></section>
   <div className="section-toolbar"><div><h2>Tu resumen</h2><p>Un vistazo a tus números</p></div><label className="month-picker"><CalendarDays/><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><ChevronDown/></label></div>
   <section className="stats-grid"><article className="stat-card"><div className="stat-top"><span>Gasto del mes</span><i className="stat-icon green"><Wallet/></i></div><strong>{money(total)}</strong><div className="stat-foot"><span className={`trend ${difference>0?'down':'up'}`}>{difference===null?<TrendingUp/>:difference>0?<ArrowUpRight/>:<ArrowDownLeft/>} {difference===null?'Primer mes':`${Math.abs(difference)}%`}</span><span>{difference===null?'registrá tus movimientos':difference>0?'más que el mes pasado':'menos que el mes pasado'}</span></div></article><article className="stat-card"><div className="stat-top"><span>Movimientos</span><i className="stat-icon lilac"><ArrowDownLeft/></i></div><strong>{visible.length}</strong><div className="stat-foot"><b>Este mes</b><span>gastos registrados</span></div></article><article className="stat-card"><div className="stat-top"><span>Mayor categoría</span><i className="stat-icon amber"><TrendingUp/></i></div><strong className="category-stat">{biggest?.name||'—'}</strong><div className="stat-foot"><b>{biggest?money(biggest.amount):'Sin datos'}</b><span>{biggest&&total?`${Math.round(biggest.amount/total*100)}% de tus gastos`:'por ahora'}</span></div></article></section>
   <section className="analysis-grid" id="categorias"><article className="panel category-panel"><div className="panel-heading"><div><h3>Gastos por categoría</h3><p>¿En qué se fue tu plata?</p></div><button className="more-button"><Ellipsis/></button></div><div className="category-content"><Donut items={grouped} total={total}/><div className="category-legend">{grouped.length?grouped.slice(0,5).map(item=><div className="legend-row" key={item.name}><i style={{background:item.color}}/><span>{item.name}</span><strong>{money(item.amount)}</strong></div>):<div className="empty-chart"><span className="empty-icon"><PieChart/></span><strong>Todavía no hay datos</strong><span>Cuando registres gastos, vas a ver acá cómo se distribuyen.</span></div>}</div></div><a className="panel-link" href="#movimientos">Ver movimientos <ArrowRight/></a></article>
   <article className="panel insight-panel"><div className="panel-heading"><div><h3>Un paso más cerca</h3><p>Pequeños hábitos, más claridad</p></div><span className="insight-spark"><Sparkles/></span></div><div className="insight-visual"><div className="insight-ring"><div><span>MES</span><strong>{new Intl.DateTimeFormat('es-AR',{month:'short'}).format(new Date(`${month}-15T12:00:00`)).replace('.','')}</strong></div></div><div className="insight-bars">{Array.from({length:9},(_,i)=><i key={i}/>)}</div></div><h4>{visible.length?'¡Buen trabajo registrando!':'Empezá con un gasto'}</h4><p>{visible.length?`Ya tenés ${visible.length} ${visible.length===1?'movimiento':'movimientos'} anotados este mes. Seguí así para entender mejor tus hábitos.`:'Anotar cada compra toma unos segundos y te ayuda a entender mejor tus hábitos.'}</p><button className="insight-action" onClick={()=>document.querySelector('.quick-form input')?.focus()}>{visible.length?'Registrar otro gasto':'Anotar mi primer gasto'} <ArrowRight/></button></article></section>
   <section className="money-panels" id="finanzas"><article className="panel finance-panel"><div className="panel-heading"><div><h3>Ingresos y disponible</h3><p>Sueldo, cobros y dinero invertido este mes</p></div><span className="finance-tag"><Wallet/> {month}</span></div><div className="finance-inputs"><label>Sueldo del mes<div className="currency-field"><span>$</span><input type="number" min="0" step="0.01" value={monthlyFinance.salary||''} onChange={e=>setMonthly('salary',Number(e.target.value))} placeholder="0"/></div></label><label>Cobros de internet<div className="currency-field"><span>$</span><input type="number" min="0" step="0.01" value={monthlyFinance.internet||''} onChange={e=>setMonthly('internet',Number(e.target.value))} placeholder="0"/></div></label><label>Invertido este mes<div className="currency-field"><span>$</span><input type="number" min="0" step="0.01" value={monthlyFinance.investments||''} onChange={e=>setMonthly('investments',Number(e.target.value))} placeholder="0"/></div></label>{month.endsWith('-01')&&Number(month.slice(0,4))===firstYear&&<label>Saldo inicial de enero<div className="currency-field"><span>$</span><input type="number" step="0.01" value={monthlyFinance.openingBalance||''} onChange={e=>setMonthly('openingBalance',Number(e.target.value))} placeholder="0"/></div></label>}</div><div className="balance-strip"><div><span>Saldo anterior</span><strong>{money(carried)}</strong></div><i>+</i><div><span>Sueldo + internet</span><strong>{money(Number(monthlyFinance.salary||0)+Number(monthlyFinance.internet||0))}</strong></div><i>−</i><div><span>Gastos + inversión</span><strong>{money(total+Number(monthlyFinance.investments||0))}</strong></div><div className="available-balance"><span>Disponible</span><strong>{money(available)}</strong></div></div><p className="formula-note">Disponible = saldo anterior + sueldo + cobros de internet − gastos del mes − inversiones</p></article>
   <article className="panel closing-panel" id="tarjetas"><div className="panel-heading"><div><h3>Tarjetas y cierres</h3><p>Cierre editable para cada tarjeta y mes</p></div><CreditCard className="closing-icon"/></div><div className="card-closing-list">{creditCards.filter(c=>c!=='Otra tarjeta').map(card=>{const spent=cardTotals.find(x=>x.card===card)?.amount||0;return <div className="card-closing-row" key={card}><div className="bank-mark">{card==='YOY'?'Y':card.startsWith('Visa')?'V':card.startsWith('Master')?'M':'G'}</div><div className="bank-info"><strong>{card}</strong><span>Gastos que entran este mes</span><b>{money(spent)}</b></div><label className="close-control"><span>Cierra</span><input type="date" value={closeDate(card,month,closings)} onChange={e=>setClosing(card,e.target.value)}/></label></div>})}</div><p className="formula-note">Referencias del Excel: YOY día 23, Galicia día 30. Compra en o después del cierre → primer cargo al mes siguiente.</p></article></section>   <section className="panel transactions-panel" id="movimientos"><div className="panel-heading transaction-heading"><div><h3>Movimientos recientes</h3><p>Los últimos gastos que registraste</p></div><div className="transaction-actions"><label className="search-field"><Search/><input placeholder="Buscar" onChange={e=>setFilter(e.target.value?'search:'+e.target.value.toLowerCase():'Todos')}/></label><button className="filter-button" onClick={()=>setFilter(filter==='Todos'?'YOY':'Todos')}>{filter==='Todos'?'Tarjeta YOY':'Ver todos'} <ChevronDown/></button></div></div><div className="table-head"><span>DESCRIPCIÓN</span><span>CATEGORÍA</span><span>FECHA</span><span>MÉTODO</span><span>IMPORTE</span><span/></div>
    {recent.length?recent.slice(0,8).map(item=>{const category=categories.find(c=>c.name===item.category)||categories.at(-1);const Icon=category.icon;return <div className="transaction-row" key={item.id}><div className="transaction-description"><span className="transaction-icon" style={{color:category.color,background:`${category.color}16`}}><Icon/></span><strong>{item.description}{item.due.count>1&&<small className="installment-tag"> · Cuota {item.due.index}/{item.due.count} de {money(item.amount)}</small>}</strong></div><span className="category-pill"><i style={{background:category.color}}/>{item.category}</span><span className="date-cell">{new Date(`${item.date}T12:00:00`).toLocaleDateString('es-AR',{day:'2-digit',month:'short'})}</span><span className="payment-cell"><CreditCard/>{item.payment||'Sin método'}</span><strong className="amount-cell">{money(item.due.amount)}</strong><button className="delete-button" onClick={()=>persist(expenses.filter(x=>x.id!==item.id))} aria-label="Eliminar movimiento"><Trash2/></button></div>}):<div className="table-empty"><div className="empty-bag"><ShoppingBasket/></div><strong>Todavía no hay movimientos</strong><span>Cuando registres un gasto, va a aparecer acá.</span></div>}
    <div className="table-footer"><span>Mostrando <strong>{Math.min(recent.length,8)}</strong> de <strong>{recent.length}</strong> movimientos</span><button onClick={()=>{setFilter('Todos');setMonth(today().slice(0,7))}}>Ver este mes <ArrowRight/></button></div></section>
   <footer className="page-footer"><span>Hecho para tener las cuentas más claras.</span><span>Tu información queda guardada en este dispositivo <i>●</i></span></footer>
  </main>
 </div>
}









